# Generated by Django 2.1.7 on 2019-04-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
