# Generated by Django 2.1.7 on 2019-04-12 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automatedbankteller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.IntegerField()),
                ('account_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account_type', models.CharField(choices=[('SA', 'Savings'), ('CA', 'Checking'), ('MM', 'Money market'), ('CD', 'Certificates of deposit'), ('RA', 'Retirement')], max_length=2)),
                ('account_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
