# Generated by Django 2.1.7 on 2019-04-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automatedbankteller', '0006_deposit_deposit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='account_owner',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
