# Generated by Django 2.1.7 on 2019-04-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automatedbankteller', '0008_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
